// src/constants/countries.js

export const COUNTRIES_LIST = [
  { code: 'AF', flag: '🇦🇫', dialCode: '+93', nameAr: 'أفغانستان', nameEn: 'Afghanistan' },
  { code: 'DZ', flag: '🇩🇿', dialCode: '+213', nameAr: 'الجزائر', nameEn: 'Algeria' },
  { code: 'AR', flag: '🇦🇷', dialCode: '+54', nameAr: 'الأرجنتين', nameEn: 'Argentina' },
  { code: 'AU', flag: '🇦🇺', dialCode: '+61', nameAr: 'أستراليا', nameEn: 'Australia' },
  { code: 'AT', flag: '🇦🇹', dialCode: '+43', nameAr: 'النمسا', nameEn: 'Austria' },
  { code: 'AZ', flag: '🇦🇿', dialCode: '+994', nameAr: 'أذربيجان', nameEn: 'Azerbaijan' },
  { code: 'BH', flag: '🇧🇭', dialCode: '+973', nameAr: 'البحرين', nameEn: 'Bahrain' },
  { code: 'BD', flag: '🇧🇩', dialCode: '+880', nameAr: 'بنغلاديش', nameEn: 'Bangladesh' },
  { code: 'BE', flag: '🇧🇪', dialCode: '+32', nameAr: 'بلجيكا', nameEn: 'Belgium' },
  { code: 'BR', flag: '🇧🇷', dialCode: '+55', nameAr: 'البرازيل', nameEn: 'Brazil' },
  { code: 'CA', flag: '🇨🇦', dialCode: '+1', nameAr: 'كندا', nameEn: 'Canada' },
  { code: 'CN', flag: '🇨🇳', dialCode: '+86', nameAr: 'الصين', nameEn: 'China' },
  { code: 'KM', flag: '🇰🇲', dialCode: '+269', nameAr: 'جزر القمر', nameEn: 'Comoros' },
  { code: 'DJ', flag: '🇩🇯', dialCode: '+253', nameAr: 'جيبوتي', nameEn: 'Djibouti' },
  { code: 'EG', flag: '🇪🇬', dialCode: '+20', nameAr: 'مصر', nameEn: 'Egypt' },
  { code: 'ET', flag: '🇪🇹', dialCode: '+251', nameAr: 'إثيوبيا', nameEn: 'Ethiopia' },
  { code: 'FI', flag: '🇫🇮', dialCode: '+358', nameAr: 'فنلندا', nameEn: 'Finland' },
  { code: 'FR', flag: '🇫🇷', dialCode: '+33', nameAr: 'فرنسا', nameEn: 'France' },
  { code: 'DE', flag: '🇩🇪', dialCode: '+49', nameAr: 'ألمانيا', nameEn: 'Germany' },
  { code: 'GH', flag: '🇬🇭', dialCode: '+233', nameAr: 'غانا', nameEn: 'Ghana' },
  { code: 'IN', flag: '🇮🇳', dialCode: '+91', nameAr: 'الهند', nameEn: 'India' },
  { code: 'ID', flag: '🇮🇩', dialCode: '+62', nameAr: 'إندونيسيا', nameEn: 'Indonesia' },
  { code: 'IR', flag: '🇮🇷', dialCode: '+98', nameAr: 'إيران', nameEn: 'Iran' },
  { code: 'IQ', flag: '🇮🇶', dialCode: '+964', nameAr: 'العراق', nameEn: 'Iraq' },
  { code: 'IT', flag: '🇮🇹', dialCode: '+39', nameAr: 'إيطاليا', nameEn: 'Italy' },
  { code: 'JP', flag: '🇯🇵', dialCode: '+81', nameAr: 'اليابان', nameEn: 'Japan' },
  { code: 'JO', flag: '🇯🇴', dialCode: '+962', nameAr: 'الأردن', nameEn: 'Jordan' },
  { code: 'KZ', flag: '🇰🇿', dialCode: '+7', nameAr: 'كازاخستان', nameEn: 'Kazakhstan' },
  { code: 'KE', flag: '🇰🇪', dialCode: '+254', nameAr: 'كينيا', nameEn: 'Kenya' },
  { code: 'KW', flag: '🇰🇼', dialCode: '+965', nameAr: 'الكويت', nameEn: 'Kuwait' },
  { code: 'LB', flag: '🇱🇧', dialCode: '+961', nameAr: 'لبنان', nameEn: 'Lebanon' },
  { code: 'LY', flag: '🇱🇾', dialCode: '+218', nameAr: 'ليبيا', nameEn: 'Libya' },
  { code: 'MY', flag: '🇲🇾', dialCode: '+60', nameAr: 'ماليزيا', nameEn: 'Malaysia' },
  { code: 'MR', flag: '🇲🇷', dialCode: '+222', nameAr: 'موريتانيا', nameEn: 'Mauritania' },
  { code: 'MX', flag: '🇲🇽', dialCode: '+52', nameAr: 'المكسيك', nameEn: 'Mexico' },
  { code: 'MA', flag: '🇲🇦', dialCode: '+212', nameAr: 'المغرب', nameEn: 'Morocco' },
  { code: 'NL', flag: '🇳🇱', dialCode: '+31', nameAr: 'هولندا', nameEn: 'Netherlands' },
  { code: 'NZ', flag: '🇳🇿', dialCode: '+64', nameAr: 'نيوزيلندا', nameEn: 'New Zealand' },
  { code: 'NG', flag: '🇳🇬', dialCode: '+234', nameAr: 'نيجريا', nameEn: 'Nigeria' },
  { code: 'NO', flag: '🇳🇴', dialCode: '+47', nameAr: 'النرويج', nameEn: 'Norway' },
  { code: 'OM', flag: '🇴🇲', dialCode: '+968', nameAr: 'عُمان', nameEn: 'Oman' },
  { code: 'PK', flag: '🇵🇰', dialCode: '+92', nameAr: 'باكستان', nameEn: 'Pakistan' },
  { code: 'PS', flag: '🇵🇸', dialCode: '+970', nameAr: 'فلسطين', nameEn: 'Palestine' },
  { code: 'QA', flag: '🇶🇦', dialCode: '+974', nameAr: 'قطر', nameEn: 'Qatar' },
  { code: 'RU', flag: '🇷🇺', dialCode: '+7', nameAr: 'روسيا', nameEn: 'Russia' },
  { code: 'SA', flag: '🇸🇦', dialCode: '+966', nameAr: 'المملكة العربية السعودية', nameEn: 'Saudi Arabia' },
  { code: 'SN', flag: '🇸🇳', dialCode: '+221', nameAr: 'السنغال', nameEn: 'Senegal' },
  { code: 'SG', flag: '🇸🇬', dialCode: '+65', nameAr: 'سنغافورة', nameEn: 'Singapore' },
  { code: 'SO', flag: '🇸🇴', dialCode: '+252', nameAr: 'الصومال', nameEn: 'Somalia' },
  { code: 'ZA', flag: '🇿🇦', dialCode: '+27', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa' },
  { code: 'KR', flag: '🇰🇷', dialCode: '+82', nameAr: 'كوريا الجنوبية', nameEn: 'South Korea' },
  { code: 'ES', flag: '🇪🇸', dialCode: '+34', nameAr: 'إسبانيا', nameEn: 'Spain' },
  { code: 'SD', flag: '🇸🇩', dialCode: '+249', nameAr: 'السودان', nameEn: 'Sudan' },
  { code: 'SE', flag: '🇸🇪', dialCode: '+46', nameAr: 'السويد', nameEn: 'Sweden' },
  { code: 'CH', flag: '🇨🇭', dialCode: '+41', nameAr: 'سويسرا', nameEn: 'Switzerland' },
  { code: 'SY', flag: '🇸🇾', dialCode: '+963', nameAr: 'سوريا', nameEn: 'Syria' },
  { code: 'TN', flag: '🇹🇳', dialCode: '+216', nameAr: 'تونس', nameEn: 'Tunisia' },
  { code: 'TR', flag: '🇹🇷', dialCode: '+90', nameAr: 'تركيا', nameEn: 'Turkey' },
  { code: 'AE', flag: '🇦🇪', dialCode: '+971', nameAr: 'الإمارات العربية المتحدة', nameEn: 'United Arab Emirates' },
  { code: 'GB', flag: '🇬🇧', dialCode: '+44', nameAr: 'المملكة المتحدة', nameEn: 'United Kingdom' },
  { code: 'US', flag: '🇺🇸', dialCode: '+1', nameAr: 'الولايات المتحدة الأمريكية', nameEn: 'United States' },
  { code: 'UZ', flag: '🇺🇿', dialCode: '+998', nameAr: 'أوزبكستان', nameEn: 'Uzbekistan' },
  { code: 'YE', flag: '🇾🇪', dialCode: '+967', nameAr: 'اليمن', nameEn: 'Yemen' }
  { code: 'ML', flag: '🇲🇱', dialCode: '+223', nameAr: 'مالي', nameEn: 'Mali' },
  { code: 'NE', flag: '🇳🇪', dialCode: '+227', nameAr: 'النيجر', nameEn: 'Niger' },
  
];
