// src/constants/countries.js

export const COUNTRIES_LIST = [
  { code: 'AF', flag: '🇦🇫', dialCode: '+93', timezone: 'Asia/Kabul', nameAr: 'أفغانستان', nameEn: 'Afghanistan' },
  { code: 'DZ', flag: '🇩🇿', dialCode: '+213', timezone: 'Africa/Algiers', nameAr: 'الجزائر', nameEn: 'Algeria' },
  { code: 'AR', flag: '🇦🇷', dialCode: '+54', timezone: 'America/Argentina/Buenos_Aires', nameAr: 'الأرجنتين', nameEn: 'Argentina' },
  { code: 'AU', flag: '🇦🇺', dialCode: '+61', timezone: 'Australia/Sydney', nameAr: 'أستراليا', nameEn: 'Australia' },
  { code: 'AT', flag: '🇦🇹', dialCode: '+43', timezone: 'Europe/Vienna', nameAr: 'النمسا', nameEn: 'Austria' },
  { code: 'AZ', flag: '🇦🇿', dialCode: '+994', timezone: 'Asia/Baku', nameAr: 'أذربيجان', nameEn: 'Azerbaijan' },
  { code: 'BH', flag: '🇧🇭', dialCode: '+973', timezone: 'Asia/Bahrain', nameAr: 'البحرين', nameEn: 'Bahrain' },
  { code: 'BD', flag: '🇧🇩', dialCode: '+880', timezone: 'Asia/Dhaka', nameAr: 'بنغلاديش', nameEn: 'Bangladesh' },
  { code: 'BE', flag: '🇧🇪', dialCode: '+32', timezone: 'Europe/Brussels', nameAr: 'بلجيكا', nameEn: 'Belgium' },
  { code: 'BR', flag: '🇧🇷', dialCode: '+55', timezone: 'America/Sao_Paulo', nameAr: 'البرازيل', nameEn: 'Brazil' },
  { code: 'CA', flag: '🇨🇦', dialCode: '+1', timezone: 'America/Toronto', nameAr: 'كندا', nameEn: 'Canada' },
  { code: 'CN', flag: '🇨🇳', dialCode: '+86', timezone: 'Asia/Shanghai', nameAr: 'الصين', nameEn: 'China' },
  { code: 'KM', flag: '🇰🇲', dialCode: '+269', timezone: 'Indian/Comoro', nameAr: 'جزر القمر', nameEn: 'Comoros' },
  { code: 'DJ', flag: '🇩🇯', dialCode: '+253', timezone: 'Africa/Djibouti', nameAr: 'جيبوتي', nameEn: 'Djibouti' },
  { code: 'EG', flag: '🇪🇬', dialCode: '+20', timezone: 'Africa/Cairo', nameAr: 'مصر', nameEn: 'Egypt' },
  { code: 'ET', flag: '🇪🇹', dialCode: '+251', timezone: 'Africa/Addis_Ababa', nameAr: 'إثيوبيا', nameEn: 'Ethiopia' },
  { code: 'FI', flag: '🇫🇮', dialCode: '+358', timezone: 'Europe/Helsinki', nameAr: 'فنلندا', nameEn: 'Finland' },
  { code: 'FR', flag: '🇫🇷', dialCode: '+33', timezone: 'Europe/Paris', nameAr: 'فرنسا', nameEn: 'France' },
  { code: 'DE', flag: '🇩🇪', dialCode: '+49', timezone: 'Europe/Berlin', nameAr: 'ألمانيا', nameEn: 'Germany' },
  { code: 'GH', flag: '🇬🇭', dialCode: '+233', timezone: 'Africa/Accra', nameAr: 'غانا', nameEn: 'Ghana' },
  { code: 'IN', flag: '🇮🇳', dialCode: '+91', timezone: 'Asia/Kolkata', nameAr: 'الهند', nameEn: 'India' },
  { code: 'ID', flag: '🇮🇩', dialCode: '+62', timezone: 'Asia/Jakarta', nameAr: 'إندونيسيا', nameEn: 'Indonesia' },
  { code: 'IR', flag: '🇮🇷', dialCode: '+98', timezone: 'Asia/Tehran', nameAr: 'إيران', nameEn: 'Iran' },
  { code: 'IQ', flag: '🇮🇶', dialCode: '+964', timezone: 'Asia/Baghdad', nameAr: 'العراق', nameEn: 'Iraq' },
  { code: 'IT', flag: '🇮🇹', dialCode: '+39', timezone: 'Europe/Rome', nameAr: 'إيطاليا', nameEn: 'Italy' },
  { code: 'JP', flag: '🇯🇵', dialCode: '+81', timezone: 'Asia/Tokyo', nameAr: 'اليابان', nameEn: 'Japan' },
  { code: 'JO', flag: '🇯🇴', dialCode: '+962', timezone: 'Asia/Amman', nameAr: 'الأردن', nameEn: 'Jordan' },
  { code: 'KZ', flag: '🇰🇿', dialCode: '+7', timezone: 'Asia/Almaty', nameAr: 'كازاخستان', nameEn: 'Kazakhstan' },
  { code: 'KE', flag: '🇰🇪', dialCode: '+254', timezone: 'Africa/Nairobi', nameAr: 'كينيا', nameEn: 'Kenya' },
  { code: 'KW', flag: '🇰🇼', dialCode: '+965', timezone: 'Asia/Kuwait', nameAr: 'الكويت', nameEn: 'Kuwait' },
  { code: 'LB', flag: '🇱🇧', dialCode: '+961', timezone: 'Asia/Beirut', nameAr: 'لبنان', nameEn: 'Lebanon' },
  { code: 'LY', flag: '🇱🇾', dialCode: '+218', timezone: 'Africa/Tripoli', nameAr: 'ليبيا', nameEn: 'Libya' },
  { code: 'MY', flag: '🇲🇾', dialCode: '+60', timezone: 'Asia/Kuala_Lumpur', nameAr: 'ماليزيا', nameEn: 'Malaysia' },
  { code: 'MR', flag: '🇲🇷', dialCode: '+222', timezone: 'Africa/Nouakchott', nameAr: 'موريتانيا', nameEn: 'Mauritania' },
  { code: 'MX', flag: '🇲🇽', dialCode: '+52', timezone: 'America/Mexico_City', nameAr: 'المكسيك', nameEn: 'Mexico' },
  { code: 'MA', flag: '🇲🇦', dialCode: '+212', timezone: 'Africa/Casablanca', nameAr: 'المغرب', nameEn: 'Morocco' },
  { code: 'NL', flag: '🇳🇱', dialCode: '+31', timezone: 'Europe/Amsterdam', nameAr: 'هولندا', nameEn: 'Netherlands' },
  { code: 'NZ', flag: '🇳🇿', dialCode: '+64', timezone: 'Pacific/Auckland', nameAr: 'نيوزيلندا', nameEn: 'New Zealand' },
  { code: 'NG', flag: '🇳🇬', dialCode: '+234', timezone: 'Africa/Lagos', nameAr: 'نيجريا', nameEn: 'Nigeria' },
  { code: 'NO', flag: '🇳🇴', dialCode: '+47', timezone: 'Europe/Oslo', nameAr: 'النرويج', nameEn: 'Norway' },
  { code: 'OM', flag: '🇴🇲', dialCode: '+968', timezone: 'Asia/Muscat', nameAr: 'عُمان', nameEn: 'Oman' },
  { code: 'PK', flag: '🇵🇰', dialCode: '+92', timezone: 'Asia/Karachi', nameAr: 'باكستان', nameEn: 'Pakistan' },
  { code: 'PS', flag: '🇵🇸', dialCode: '+970', timezone: 'Asia/Gaza', nameAr: 'فلسطين', nameEn: 'Palestine' },
  { code: 'QA', flag: '🇶🇦', dialCode: '+974', timezone: 'Asia/Qatar', nameAr: 'قطر', nameEn: 'Qatar' },
  { code: 'RU', flag: '🇷🇺', dialCode: '+7', timezone: 'Europe/Moscow', nameAr: 'روسيا', nameEn: 'Russia' },
  { code: 'SA', flag: '🇸🇦', dialCode: '+966', timezone: 'Asia/Riyadh', nameAr: 'المملكة العربية السعودية', nameEn: 'Saudi Arabia' },
  { code: 'SN', flag: '🇸🇳', dialCode: '+221', timezone: 'Africa/Dakar', nameAr: 'السنغال', nameEn: 'Senegal' },
  { code: 'SG', flag: '🇸🇬', dialCode: '+65', timezone: 'Asia/Singapore', nameAr: 'سنغافورة', nameEn: 'Singapore' },
  { code: 'SO', flag: '🇸🇴', dialCode: '+252', timezone: 'Africa/Mogadishu', nameAr: 'الصومال', nameEn: 'Somalia' },
  { code: 'ZA', flag: '🇿🇦', dialCode: '+27', timezone: 'Africa/Johannesburg', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa' },
  { code: 'KR', flag: '🇰🇷', dialCode: '+82', timezone: 'Asia/Seoul', nameAr: 'كوريا الجنوبية', nameEn: 'South Korea' },
  { code: 'ES', flag: '🇪🇸', dialCode: '+34', timezone: 'Europe/Madrid', nameAr: 'إسبانيا', nameEn: 'Spain' },
  { code: 'SD', flag: '🇸🇩', dialCode: '+249', timezone: 'Africa/Khartoum', nameAr: 'السودان', nameEn: 'Sudan' },
  { code: 'SE', flag: '🇸🇪', dialCode: '+46', timezone: 'Europe/Stockholm', nameAr: 'السويد', nameEn: 'Sweden' },
  { code: 'CH', flag: '🇨🇭', dialCode: '+41', timezone: 'Europe/Zurich', nameAr: 'سويسرا', nameEn: 'Switzerland' },
  { code: 'SY', flag: '🇸🇾', dialCode: '+963', timezone: 'Asia/Damascus', nameAr: 'سوريا', nameEn: 'Syria' },
  { code: 'TN', flag: '🇹🇳', dialCode: '+216', timezone: 'Africa/Tunis', nameAr: 'تونس', nameEn: 'Tunisia' },
  { code: 'TR', flag: '🇹🇷', dialCode: '+90', timezone: 'Europe/Istanbul', nameAr: 'تركيا', nameEn: 'Turkey' },
  { code: 'AE', flag: '🇦🇪', dialCode: '+971', timezone: 'Asia/Dubai', nameAr: 'الإمارات العربية المتحدة', nameEn: 'United Arab Emirates' },
  { code: 'GB', flag: '🇬🇧', dialCode: '+44', timezone: 'Europe/London', nameAr: 'المملكة المتحدة', nameEn: 'United Kingdom' },
  { code: 'US', flag: '🇺🇸', dialCode: '+1', timezone: 'America/New_York', nameAr: 'الولايات المتحدة الأمريكية', nameEn: 'United States' },
  { code: 'UZ', flag: '🇺🇿', dialCode: '+998', timezone: 'Asia/Tashkent', nameAr: 'أوزبكستان', nameEn: 'Uzbekistan' },
  { code: 'YE', flag: '🇾🇪', dialCode: '+967', timezone: 'Asia/Aden', nameAr: 'اليمن', nameEn: 'Yemen' },
  { code: 'ML', flag: '🇲🇱', dialCode: '+223', timezone: 'Africa/Bamako', nameAr: 'مالي', nameEn: 'Mali' },
  { code: 'NE', flag: '🇳🇪', dialCode: '+227', timezone: 'Africa/Niamey', nameAr: 'النيجر', nameEn: 'Niger' }
];

// تصدير متوافق لمنع أي تعارض مستقبلي
export const COUNTRIES = COUNTRIES_LIST;
export default COUNTRIES_LIST;
